Upload file index.html
st-longngo/FE-Internship-Summer-2022_st-longngo_FE-Exercise pull request #1
Opened 2022-06-08 09:34 UTC by st-longngo

### Description

Nộp bài tâp HTML.

2022-06-08 17:57 UTC, st-duynguyen commented on index.html
> +      <div class="header-main">
Thằng header-main a thấy không cần thiết ở đây. Class container nên nằm ngay sau thằng cha lớn nhất để bọc các phần tử con ở trong

2022-06-08 18:01 UTC, st-duynguyen commented on index.html
> +            <a class="contet-link">
sai chính tả =))

2022-06-08 18:05 UTC, st-duynguyen commented on index.html
> +            <h2 class="section-title">Selected just for you</h2>
E thêm chú ý cho việc dùng thẻ heading

Text có chứa tên brand/page sẽ dùng h1 và 1 trang sẽ chỉ có duy nhất 1 h1
Text ở banner sẽ là h2
Text ở các section title sẽ là h3
Text ở các title của list item sẽ là h4
Ở chỗ e a thấy đang dùng quá nhiều thẻ h2. Check lại rồi sửa theo comment của a nha

2022-06-08 18:07 UTC, st-duynguyen commented on index.html
> +      <div class="footer-main">
Tương tự như trên, thằng này đang bị dư k cần phải thêm 1 div này làm gì

2022-06-08 18:13 UTC, st-duynguyen requested changes
@st-longngo Bài của e khá tốt. Tuy nhiên cần sửa lại 1 vài chỗ như a nói ở dưới. Cố gắng phát huy nhé

2022-06-08 21:23 UTC, st-longngo commented on index.html
> +      <div class="footer-main">
Dạ anh. Em cảm ơn anh.

2022-06-09 04:16 UTC, st-quangnguyen2 commented on index.html
> +                /></a>
format lại code phần này, kiểm tra và format lại với các phần bị tương tự.

2022-06-09 04:54 UTC, st-longngo commented on index.html
> +                /></a>
Dạ em mới format lại. Anh check giúp em với.

2022-06-09 17:54 UTC, st-duynguyen requested changes
LGTM! Ngày mai sửa lại format description theo a gửi trên slack nha. Và chú ý mỗi msg của commit nên viết cẩn thận, tóm tắt đc nội dung của commit, không nên viết cho có nha.

2022-06-10 06:44 UTC, st-duynguyen approved these changes
LGTM

2022-06-10 06:44 UTC, merged