Implement of Style CSS for Eshop Page
st-longngo/FE-Internship-Summer-2022_st-longngo_FE-Exercise pull request #2
Opened 2022-06-11 11:21 UTC by st-longngo

#### References

#### Description
- Implement of Style CSS for Eshop Page
#### Screenshots
#### Checklist
- [x] Code đã được build và test ở môi trường local.
- [x] Tất cả những lỗi cơ bản đã được tìm thấy và sửa chữa.

2022-06-13 09:12 UTC, st-quangnguyen2 requested changes

2022-06-13 09:12 UTC, st-quangnguyen2 commented on index.html
> +            </svg>
không dùng thẳng `svg` trong file `html`. chỗ này em dùng `img`. các chỗ cần icon thì dùng thẻ `i` rồi style. có thể tạo `module icon` để tái sử dụng.

2022-06-13 09:12 UTC, st-quangnguyen2 commented on styles.css
> +}
tổ chức lại thứ tự `css`. em tham khảo [link](https://medium.com/swlh/better-ways-to-organise-css-properties-9a066e7ded62) này rồi áp dụng hết cho các file `css`.

2022-06-13 09:45 UTC, st-longngo commented on index.html
> +            </svg>
Em không hiểu chỗ này lắm anh. Tức là mình tải file svg của icon về rồi import vào folder images rồi dùng <img src={file.svg}/> như này hả anh.

2022-06-13 09:49 UTC, st-quangnguyen2 commented on index.html
> +            </svg>
@st-longngo đúng rồi đấy, em dùng như mấy file `jpg`, `png`

2022-06-13 09:54 UTC, st-longngo commented on index.html
> +            </svg>
Dạ anh.

2022-06-13 15:41 UTC, st-duynguyen commented on common.css
> +  margin-left: -10px;
Handle shorthand cho nó. Ex: `margin: 0 -10px;`

2022-06-13 15:42 UTC, st-duynguyen commented on common.css
> +  padding-left: 10px;
Handle shorthand cho nó. Ex: `padding: 0 10px;`

2022-06-13 15:48 UTC, st-duynguyen commented on common.css
> +    margin-right: -4px;
Handle shorthand cho nó

2022-06-13 15:48 UTC, st-duynguyen commented on common.css
> +    padding-left: 4px;
Handle shorthand cho nó.

2022-06-13 16:27 UTC, st-duynguyen commented on styles.css
> +.overlay {
Chỗ này em dùng pseudo after để handle. Không cần thằng overlay

2022-06-13 16:34 UTC, st-duynguyen commented on common.css
> +.badge-primary {
Check lại design, màu trong design là màu đỏ
![Screen Shot 2022-06-13 at 11 34 48 PM](https://user-images.githubusercontent.com/62866904/173401719-81f7a5f9-161d-4b8e-accc-66cc3e5a3ef0.png)

2022-06-13 16:35 UTC, st-duynguyen commented on index.html
> +      <section class="section section-product-selected">
Check lại design, padding chỗ này chưa đúng

2022-06-13 16:38 UTC, st-duynguyen commented on styles.css
> +.footer-iso-logo {
Check lại màu của logo

2022-06-13 16:50 UTC, st-duynguyen requested changes
Check comment của a nghe

2022-06-14 07:42 UTC, st-duynguyen approved these changes
LGTM

2022-06-14 07:42 UTC, merged